# This is a basic workflow to help you get started with Actions
on:
  push:
    branches:
      - "master" # change to the branch you wish to deploy from

permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DEMSCRIPTEN=ON
    - run: cmake --build build --config ${{env.BUILD_TYPE}}
    - uses: actions/upload-artifact@master
      with:
        name: page
        path: build
        if-no-files-found: error
    - id: build-publish
      uses: bitovi/github-actions-react-to-github-pages@v1.2.4
      with:
        path: build # change to your build folder
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
      
    steps:
    - uses: actions/download-artifact@master
      with:
        name: page
        path: .
    - uses: actions/configure-pages@v1
    - uses: actions/upload-pages-artifact@v1
      with:
        path: .
    - id: deployment
      uses: actions/deploy-pages@main
    
